# Generated by Django 6.0.5 on 2026-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='topic',
            field=models.CharField(choices=[('behavioral', 'Behavioral'), ('python', 'Python / Django Development'), ('system_design', 'System Design'), ('data_structures', 'Data Structures & Algorithms'), ('c_prog', 'C Programming'), ('cpp_prog', 'C++ Programming'), ('java_prog', 'Java Programming'), ('web_dev', 'Web Development (Full Stack Basics)'), ('react_dev', 'React Development'), ('dbms', 'Database Systems'), ('sql_db', 'PostgreSQL / MySQL'), ('os', 'Operating Systems'), ('networks', 'Computer Networks'), ('cybersecurity', 'Cyber Security Basics'), ('cloud_devops', 'Cloud & DevOps Basics'), ('sys_prog', 'System Programming Concepts')], max_length=50),
        ),
    ]
