# Generated by Django 6.0.5 on 2026-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interviewsession_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('written', 'Written Response'), ('coding', 'Coding Challenge')], default='written', max_length=15),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='mode',
            field=models.CharField(choices=[('mixed', 'Mixed Mode'), ('mcq', 'MCQ Practice'), ('written', 'Written Interview'), ('coding', 'Coding Simulation')], default='mixed', max_length=20),
        ),
    ]
